import { TaskProvider } from "@/context/TaskContext";
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "Task Manager App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>
          <NavBar />
          {children}
        </TaskProvider>
      </body>
    </html>
  );
}
